name: Skywars
version: 1.0
Author: Atlas97
main: tk.icedev.heavenEncounter.Main
commands:
        skywars:
          description: Perform a SkyWars command
          aliases: [sw]
          usage: |
            |--------------------------------------------|
            /skywars <subcommand>
            |--------------------------------------------|
            /skywars map create <field name> | Creates a new FieldBuilder object or overwrite an existing one
            /skywars map adminwarp | Sets the admin warp of the current FieldBuilder object
            /skywars map bind | Sets extreme for map catching
            /skywars map addspawn | Adds a spawn into the current FieldBuilder object, the current location will be taken
            /skywars map build | Confirms the FieldBuilder object configurations
            /skywars map cancel | Cancels and destroyes the current FieldBuilder
            /skywars map remove <field name> | Removes an exsisting map
            |--------------------------------------------|
            /skywars addtier <tier name> <probability> | Registers a new tier
            /skywars additem <tier name> | Registers a new item in the specified tier
            /skywars savetiers | Save tiers configurations
            |--------------------------------------------|
            /skywars newjoin <name> <trigger material> | Creates a new join point
            /skywars setspawn | Sets the spawn location
            /skywars reload | It stops all games and reload configurations
            |--------------------------------------------|
        match:
          description: Perform a game command
          aliases: [mt]
          usage: |
            |--------------------------------------------|
            /match <subcommand>
            |--------------------------------------------|
            /match warp <id> | It teleports to the map admin warp
            /match start <field name> | Starts a new game, random if no field is specified
            /match stop <id> | Interrupts a running game
            |--------------------------------------------|
            /match list | List all the running games
            /match join <id> | Joins a starting game, the GUI will be opened if no name or id specified
            |--------------------------------------------|
        lobby:
          description: Teleports to the lobby spawn location
          usage: /lobby
        leave:
          description: Leaves the current game
          usage: /leave
        lsgames:
          description: Lists all the running games, alias of /match list
          usage: /lsgames
        broadcast:
          description: Allows to use the global chat during a match
          usage: /broadcast <message>
          aliases: [bc]
permissions:
        skywars.bypass:
          description: Allows to execute all Skywars commands
          default: op
        skywars.map:
          description: Allows to manage map commands
          default: op
        skywars.addtier:
          description: Allows to add a new tier
          default: op
        skywars.additem:
          description: Allows to add items to chests
          default: op
        skywars.savetiers:
          description: Allows to save tiers configurations
          default: op
        skywars.newjoin:
          description: Allows to create a join point
          default: op
        skywars.setspawn:
          description: Allows to set the hub spawn
          default: op
        skywars.reload:
          description: Allows to reload the skywars configurations
          default: op
        skywars.board.*:
          description: Determines how is the name shown in the board
          default: false
        skywars.chat.*:
          description: Determines the chat design 
          default: false
        skywars.match.warp:
          description: Allows to warp a running game
          default: op
        skywars.match.start:
          description: Allows to start games
          default: op
        skywars.match.stop:
          description: Allows to stop games
          default: op
        skywars.match.list:
          description: Allows to list running games
          default: true
        skywars.match.join:
          description: Allows to join a game and open the GUI
          default: true
        skywars.lobby:
          description: Allows to teleport to the spawn
          default: true
        skywars.hub.build:
          description: Allows to place and destroy blocks at the spawn
          default: op
        skywars.hub.hit:
          description: Allows to hit other players at the spawn
          default: op
        skywars.leave:
          description: Allows to leave a game
          default: true
        skywars.broadcast:
          description: Allows to send global messages
          default: true